sudo: required
dist: trusty
language: go

go:
  - "1.10.1"

addons:
  postgresql: "9.6"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

before_script:
  - psql -U postgres -c 'create database pushpop_test;'
  - psql -U postgres -c 'create database pushpop_example;'

script:
  - make test
  - make run-example
